# Copyright 2025 Michael Hanline
# SPDX-License-Identifier: Apache-2.0
#################################################################
## 
## Notifies you if the Sigenergy system goes off-grid
## Ignores unknown/unavailable events.
## 
#################################################################

alias: Sigenergy Off-Grid Notification
description: >-
  Notifies if Sigenergy system goes off-grid. Set to send an in-app
  notification
triggers:
  - trigger: state
    entity_id:
      - sensor.sigen_plant_grid_connection_status
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
conditions: []
actions:
  - action: notify.notify
    metadata: {}
    data:
      message: >-
        System went from {{ trigger.from_state.state }} to {{
        trigger.to_state.state }}
mode: single