# Copyright 2025 Michael Hanline
# SPDX-License-Identifier: Apache-2.0
#################################################################
## 
## Notify if grid import is happening during a set period.
## Uses the demand window from Amber Express as a condition
## Uses an average sensor for grid import, to filter out small,
## spiky imports
#################################################################
alias: Grid Import Notification High
description: >-
  Sends a notification if the Sigenergy system is importing from the grid during
  peak times (such as during demand window)
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.grid_import_average_sensor
    above: 0.5
conditions:
  - condition: state
    entity_id:
      - binary_sensor.amber_express_your_sensor_demand_window
    state:
      - 'on'
actions:
# Customise your actions here. I have a Shelly relay that uses an on-device
# script that flashes the light on/off three times
  - action: button.press
    metadata: {}
    target:
      entity_id: button.hallway_kitchen_switches_flash_output_0
    data: {}
  - action: persistent_notification.create
    metadata: {}
    data:
      message: >-
        Grid importing during demand period ${{ trigger.to_state.state|float(0)
        }}kwh
  - action: notify.send_message
    metadata:
      description: Send email using smtp
    target:
      entity_id: notify.smtp_notify_homeassistant_smtp
    data:
      message: >-
        Grid importing during demand period ${{ trigger.to_state.state|float(0)
        }}kwh
mode: single